Repository notion-dotnet/notion-sdk-net, pull requests merged in 2023-10, with the labels that each got.

#391 Add support for querying wiki databases
  Src/Notion.Client/Api/Databases/DatabasesClient.cs
  Src/Notion.Client/Api/Databases/IDatabasesClient.cs
  Src/Notion.Client/Api/Databases/Query/DatabasesClient.cs
  Src/Notion.Client/Api/Databases/Query/Request/DatabasesQueryParameters.cs
  Src/Notion.Client/Api/Databases/Query/Request/IDatabaseQueryBodyParameters.cs
  Src/Notion.Client/Api/Databases/Query/Request/IDatabaseQueryQueryParameters.cs
  Src/Notion.Client/Api/Databases/Query/Response/DatabaseQueryResponse.cs
  Src/Notion.Client/Models/Database/Database.cs
  Src/Notion.Client/Models/Database/IWikiDatabase.cs
  Src/Notion.Client/Models/Page/Page.cs
  Test/Notion.IntegrationTests/DatabasesClientTests.cs
  Test/Notion.UnitTests/DatabasesClientTests.cs
Labels: enhancement, feature

#392 Add support for create token endpoint
  Src/Notion.Client/Api/ApiEndpoints.cs
  Src/Notion.Client/Api/Authentication/AuthenticationClient.cs
  Src/Notion.Client/Api/Authentication/CreateToken/AuthenticationClient.cs
  Src/Notion.Client/Api/Authentication/CreateToken/Request/CreateTokenRequest.cs
  Src/Notion.Client/Api/Authentication/CreateToken/Request/ExternalAccount.cs
  Src/Notion.Client/Api/Authentication/CreateToken/Request/ICreateTokenBodyParameters.cs
  Src/Notion.Client/Api/Authentication/CreateToken/Response/CreateTokenResponse.cs
  Src/Notion.Client/Api/Authentication/IAuthenticationClient.cs
  Src/Notion.Client/NotionClient.cs
  Src/Notion.Client/NotionClientFactory.cs
Labels: enhancement, hacktoberfest-accepted, feature

#393 #390: Add missing property in paginated response
  Src/Notion.Client/Api/Comments/Retrieve/Response/Comments.cs
  Src/Notion.Client/Models/PaginatedList.cs
Labels: enhancement, hacktoberfest-accepted, feature

#395 Add type specific pagination information
  Src/Notion.Client/Api/Blocks/AppendChildren/BlocksClient.cs
  Src/Notion.Client/Api/Blocks/AppendChildren/Request/BlockAppendChildrenRequest.cs
  Src/Notion.Client/Api/Blocks/AppendChildren/Request/IBlockAppendChildrenBodyParameters.cs
  Src/Notion.Client/Api/Blocks/AppendChildren/Request/IBlockAppendChildrenPathParameters.cs
  Src/Notion.Client/Api/Blocks/AppendChildren/Response/AppendChildrenResponse.cs
  Src/Notion.Client/Api/Blocks/BlocksClient.cs
  Src/Notion.Client/Api/Blocks/IBlocksClient.cs
  Src/Notion.Client/Api/Blocks/RequestParams/BlocksRetrieveChildrenParameters.cs
  Src/Notion.Client/Api/Blocks/RequestParams/IBlocksRetrieveChildrenQueryParameters.cs
  Src/Notion.Client/Api/Blocks/RetrieveChildren/BlocksClient.cs
  Src/Notion.Client/Api/Blocks/RetrieveChildren/Request/BlockRetrieveChildrenRequest.cs
  Src/Notion.Client/Api/Blocks/RetrieveChildren/Request/IBlockRetrieveChildrenPathParameters.cs
  Src/Notion.Client/Api/Blocks/RetrieveChildren/Request/IBlockRetrieveChildrenQueryParameters.cs
  Src/Notion.Client/Api/Blocks/RetrieveChildren/Response/RetrieveChildrenResponse.cs
  Src/Notion.Client/Api/Databases/Query/Response/DatabaseQueryResponse.cs
  Src/Notion.Client/Api/Search/ISearchClient.cs
  Src/Notion.Client/Api/Search/Request/ISearchBodyParameters.cs
  Src/Notion.Client/Api/Search/Request/SearchDirection.cs
  Src/Notion.Client/Api/Search/Request/SearchFilter.cs
  Src/Notion.Client/Api/Search/Request/SearchObjectType.cs
  Src/Notion.Client/Api/Search/Request/SearchRequest.cs
  Src/Notion.Client/Api/Search/Request/SearchSort.cs
  Src/Notion.Client/Api/Search/Response/SearchResponse.cs
  Src/Notion.Client/Api/Search/SearchClient.cs
  Src/Notion.Client/Api/Users/IUsersClient.cs
  Src/Notion.Client/Api/Users/List/Request/ListUsersRequest.cs
  Src/Notion.Client/Api/Users/List/Response/ListUsersResponse.cs
  Src/Notion.Client/Api/Users/List/UsersClient.cs
  Src/Notion.Client/Api/Users/UsersClient.cs
  Test/Notion.IntegrationTests/IBlocksClientTests.cs
  Test/Notion.UnitTests/BlocksClientTests.cs
  Test/Notion.UnitTests/SearchClientTest.cs
Labels: enhancement, hacktoberfest-accepted, feature

#399 Add wrapper class to avoid sending block id as part of request body
  Src/Notion.Client/Api/Blocks/AppendChildren/BlocksClient.cs
  Src/Notion.Client/Api/Blocks/AppendChildren/Request/IBlockAppendChildrenBodyParameters.cs
Labels: fix

#400 Adjust breaking integration tests
  Test/Notion.IntegrationTests/BlocksClientTests.cs
  Test/Notion.IntegrationTests/CommentsClientTests.cs
  Test/Notion.IntegrationTests/DatabasesClientTests.cs
  Test/Notion.IntegrationTests/PageClientTests.cs
  Test/Notion.IntegrationTests/PageWithPageParentTests.cs
Labels: hacktoberfest-accepted, chore
